### ISSUE TITLE
How to close aiohttp session created by BaseBot?

### ISSUE THREAD

**Issue by HMaker** [aiogram/aiogram#1051]
`BaseBot.close()` is deprecated and will be changed on aiogram 3
https://github.com/aiogram/aiogram/blob/8604ab7cd05ee67fc0316afc0962904f417baac9/aiogram/bot/base.py#L207-L216

I see no other way on the public API to close the inner `_session` object. Everytime my program exits I get an unclosed session warning from aiohttp.

**Comment by evgfilim1** [comment]
Hello, @HMaker, and thanks for asking. This is one of the intended ways to close the session. The warning is here because there is a `close` method in the Bot API, so invoking `bot.close` in 3.0 will actually issue an API request.

To close an underlying session without getting a `DeprecationWarning`, use this code snippet: 
```python
session = await bot.get_session()
await session.close()
```
or a one-line approach, if you prefer this: `await (await bot.get_session()).close()`

https://github.com/aiogram/aiogram/blob/8604ab7cd05ee67fc0316afc0962904f417baac9/aiogram/bot/base.py#L130-L141

---
If you have further questions, you can join our Telegram chats ([listed here](https://docs.aiogram.dev/en/dev-3.x/#features)).

**Comment by HMaker** [comment]
aiogram should close the sessions it creates. I think there should be an equivalent of `bot.close()` on 3.0 which closes just the session and does any needed local cleanup.

**Comment by JrooTJunior** [comment]
> aiogram should close the sessions it creates.

aiogram is always closes the session it creates if you use it as documentation/examples says.
If you are running the code in another way you should explicitly close the session in due to aiogram has no power in you'r custom execution method.

> it should be hiden behind the public API of aiogram.

It hidden if you use it in recommended way, but if you use another way It can't be hidden it comes from two factors:
1. asyncio can't be executed on Python cleanup (object `__del__` method) because this method is not asynchronous and we cannot close in a event-loop other than the one in which the session was created.
2.  we have an Python-way to operate with session - context manager, if you using the bot or session instance outside of dispatcher you should use session context manager

Example:
```python
import asyncio

from aiogram import Bot


async def main():
    bot = Bot(token=...)
    async with bot.session:  # or `bot.context()`
        print(await bot.get_me())


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by HMaker** [comment]
I mean the way to hide behinf the public API is expose the close method like aiogram 2.x does. But the close method will be changed on 3.x, an alternative should be added like `close_local()` etc

**Comment by Olegt0rr** [comment]
In 3.x you still can close the session directly:

```python
await bot.session.close()
```
