### ISSUE TITLE
ImportError: cannot import name 'F' from 'aiogram' in examples  finite_state_machine.py

### ISSUE THREAD

**Issue by taime** [aiogram/aiogram#1136]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Mac OS
* Python Version: 3.10
* aiogram version: 2.25.1
* aiohttp version: 3.8.4
* uvloop version (if installed): not installed

## Expected Behavior

The example code of https://github.com/aiogram/aiogram/blob/dev-3.x/examples/finite_state_machine.py expected to work with no errors

## Current Behaviour

What is the current behavior?
Program doesn't start

## Failure Information (for bugs)
Get an error ImportError: cannot import name 'F' from 'aiogram'

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Take the code from https://github.com/aiogram/aiogram/blob/dev-3.x/examples/finite_state_machine.py
2. Try to execute it 
3. you get error: ImportError: cannot import name 'F' from 'aiogram'

**Comment by JrooTJunior** [comment]
You have installed 2.x version of framework but looking for 3.x beta examples.

If you really want to use 2.x version just look at examples directory corresponding version: https://github.com/aiogram/aiogram/tree/dev-2.x/examples

Please note that the default branch in the repository has been changed to `dev-3.x` because the official release of this version and its transition to the stable phase is approaching.
Version 2.x is currently stable, but support for it will end soon.

**Comment by AlexVigula** [comment]
правильный импорт
from aiogram import Bot, Dispatcher, F
