### ISSUE TITLE
Caption and caption_entities in MediaGroup

### ISSUE THREAD

**Issue by djimboy** [aiogram/aiogram#1165]
## Context

* Operating System: macOS 13.3.1
* Python Version: 3.9.9
* aiogram version: 3.0.0b7
* aiohttp version: 3.8.4
* uvloop version (if installed): 0.17.0

## Expected Behavior

The media group is displayed with a signature and with formatting (underline, spoiler..)

## Current Behavior

The media group is displayed with a signature, but without formatting (underline spoiler..)

## Steps to Reproduce

1. Begin MRE example and check caption received MediaGroup message
2. Remove `parse_mode="HTML"` (on line 10) from bot instance and try again 

## MRE
```python
import asyncio

from aiogram import Bot, Dispatcher, types
from aiogram.types import MessageEntity, InputMediaPhoto

bot_token = "..."
photo_id = "..."

dp = Dispatcher()
bot = Bot(token=bot_token, parse_mode="HTML")


@dp.message()
async def user_handler(message: types.Message, bot):
    text = "test hide text"

    entities = [
        MessageEntity(type="spoiler", offset=5, length=4),
        MessageEntity(type="underline", offset=5, length=4),
    ]

    medias = [
        InputMediaPhoto(media=photo_id, caption=None, caption_entities=None),
        InputMediaPhoto(media=photo_id, caption=text, caption_entities=entities),
    ]

    # First bug
    await bot.send_media_group(
        message.from_user.id,
        medias,
    )
    # Second bug
    await message.answer_media_group(medias)


async def main():
    await dp.start_polling(bot)


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.create_task(main())
    loop.run_forever()
```

**Comment by JrooTJunior** [comment]
Intended behaviour.

By default on the server side entities argument is ignored when you use `parse_mode` argument, also `Bot(..., parse_mode="HTML")` means that you use HTML for each message that you sent, but in case when you try to use entities directly both arguments will be sended to the API because this arguments doesn't know for each others and should not knows about each others on the serialization stage.

So, if you use global default parse mode and want to use entities you shoul explicitly set parse_mode=None in the methot (or object in this case).

The same behaviour can be reproduced on any other place where which `parse_mode` or `entities` arguments can be used, for example:

```python
bot = Bot(parse_mode="HTML")
...
    await message.answer(text="test", entities=[MessageEntity(type="bold", offset=0, length=4)])
```

entities will be ignored by the server side, but in the next example should works as you expects:
```python
bot = Bot(parse_mode="HTML")
...
    await message.answer(text="test", entities=[MessageEntity(type="bold", offset=0, length=4)], parse_mode=None)
```

---

Thanks for you question, feel free to open new issues if you have additional questions.
