### ISSUE TITLE
utils/markdown.py to utils/text_markup.py

### ISSUE THREAD

**Issue by doshfy** [aiogram/aiogram#1167]
It might be clearer to name utils/text_markup.py instead of utils/markdown.py, because this file includes not only not only markdown, but also html markup.

**Comment by JrooTJunior** [comment]
I agree that the name is a bit confusing at the moment, but i don't think that this module should be named as `text_markup` because we already have `text_decorations` module.

Also i think this module should be removed at all because it's only wrapper over `text_decorations` module for backward compatibility.

It may eventually be replaced by a more flexible text formatting tool, and only text_decorations will remain for simple cases. I already have prototype of entities builder (example: `Text("Hello", Bold("World")` which can be converted into message entities to use in API methods)

**Comment by JrooTJunior** [comment]
Draft: #1172

**Comment by doshfy** [comment]
It looks amazing! Good luck!

**Comment by doshfy** [comment]
It looks amazing! Good luck on develop!
