### ISSUE TITLE
Trying to forward message from a supergroup (topic) to regular group

### ISSUE THREAD

**Issue by TalKatz1** [aiogram/aiogram#1205]
**Is your feature request related to a problem? Please describe.**
I'm trying to use forward_message function to forward a message from a topic in a supergroup to a regular group.
I can't supply something like source_message_thread_id, because it's not an option in the function.
Do you know how can I do that?
When providing only the source_chat_id, message_id and destination_chat_id it returns: `Message to forward not found`

**Describe the solution you'd like**
Providing source_message_thread_id in forward_message function.

**Describe alternatives you've considered**
Don't have any for now

**Comment by JrooTJunior** [comment]
Bot API has no such kind of argument in the API in due to telegram has a single sequence of identifiers for messages in the chat and this identifiers cannot be repeated between topics, so source chat id and message id is enough to forward message.

The error `Message to forward not found` means that this message is really was missing in the chat.

---

Note that you can use Message.forward shortcut to forward any received message that you received from API: https://docs.aiogram.dev/en/dev-3.x/api/types/message.html#aiogram.types.message.Message.forward
This shortcut automatically fill all required arguments of the API method that is needed for forwarding.

**Comment by TalKatz1** [comment]
Thanks! using message.forward will solve my issue, but actually I'm having trouble running it too.
This time the error is `Can't get bot instance from context. You can fix it with setting current instance: 'Bot.set_current(bot_instance)'`

Do you know what is this about?

**Comment by TalKatz1** [comment]
First of all, thanks for the help and being so responsive! :) 


This is my code section:
```python
        message_sent = await bot.send_message(chat_id=chat_id, text=message, message_thread_id=thread_id, parse_mode='Markdown')
        log(f"Message sent successfully to topic id: {thread_id}")

        await message_sent.forward(chat_id=MY_CHAT_ID)
```

Basically sending a message to one group, it works and then I'm trying to forward it to another group, it failed.

**Comment by JrooTJunior** [comment]
Is not the answer to question where did you call this method. I mean you do it inside handlers or any other functions called anywhere outside?

Shortcuts works only when Bot instance is in the context, by default it is configured inside aiogram's Dispatcher, but if you call it outside of the handlers you should use Bot API methods directly OR setup context by himself, for example:

```python
async def do_sonemthin(bot: Bot, message: Message):
    async with bot.context():
        await message.forward(chat_id=MY_GROUP_ID)
```

But from your example it seems like you call it from the handler, so it should works as well out of the box, or just provide minimum reproducible example, that so that I can copy to my IDE and run without additional actions and check your issue.

**Comment by TalKatz1** [comment]
Here is an example that generates this error:


```
from aiogram import Bot
import asyncio


async def send_message_to_group(message, chat_id, bot_token):
    group_two = -112233445
    bot = Bot(token=bot_token)

    message_sent = await bot.send_message(chat_id=chat_id, text=message, parse_mode='HTML')

    if message == "Hello, how are you?":
        try:
            await message_sent.forward(chat_id=group_two)
        except Exception as e: 
            print(f"FAILED TO FORWARD MESSAGE: {e}")

    session = await bot.get_session()
    await session.close()
    return message_sent


if __name__ == '__main__':
    bot_token = "1234567890:xxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxx"
    group_one = -123456789
    messages_to_send = [
        "hey", "hello", "Hello, how are you?", "whats"
    ]

    for message in messages_to_send:
        asyncio.run(send_message_to_group(chat_id=group_one, message=message, bot_token=bot_token))

```

output:
```
FAILED TO FORWARD MESSAGE: Can't get bot instance from context. You can fix it with setting current instance: 'Bot.set_current(bot_instance)'
```

**Comment by JrooTJunior** [comment]
Please update aiogram to 3.0.0rc1 (in Beta 8 bot context is reworked)
Now your example should works as well.


Also i see some bad solutions in your code, let's try to fix it:

- You don't need to restart async io event loop for each message
- You don't need to create new Bot instance for each message
- You can and should use bt context manager to controll Bot session
- You shouldn't catch any `Exception`, it is too broad, you should check only specific errors that is expected for this code
- In due to Telegram has rate-limits you should wait some time between messages

So, let's put it all together:

```python
import asyncio

from aiogram import Bot
from aiogram.enums import ParseMode
from aiogram.exceptions import TelegramAPIError
from aiogram.types import Message


async def send_message_to_group(bot: Bot, text: str, chat_id: int) -> Message:
    group_two = -112233445
    message_sent = await bot.send_message(chat_id=chat_id, text=text, parse_mode=ParseMode.HTML)

    if text == "Hello, how are you?":
        try:
            await message_sent.forward(chat_id=group_two)
        except TelegramAPIError as e:
            print(f"FAILED TO FORWARD MESSAGE: {e}")

    return message_sent


async def main():
    bot_token = "1234567890:xxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxx"
    group_one = -123456789
    messages_to_send = ["hey", "hello", "Hello, how are you?", "whats"]

    async with Bot(token=bot_token).context() as bot:
        for message in messages_to_send:
            await send_message_to_group(bot=bot, chat_id=group_one, text=message)
            await asyncio.sleep(0.1)


if __name__ == "__main__":
    asyncio.run(main())
```
