### ISSUE TITLE
Redis storage fails with redis.exceptions.ConnectionError: Error UNKNOWN while writing to socket. Connection lost.

### ISSUE THREAD

**Issue by BobaZooba** [aiogram/aiogram#1218]
## Context

I have FSMStorage running on Redis. Redis, like the bot and the API, are on Digital Ocean.

Periodically, I receive this error: 
redis.exceptions.ConnectionError: Error UNKNOWN while writing to socket. Connection lost.

I thought it might be due to writing a lot to Redis. So, I replicated Redis, now there are two nodes, but the issue persists. I thought it might be due to high load, but right now there is no load and the error still appears occasionally.

Perhaps there's another issue with Redis, but the API communicates a lot with it and there are no problems. The Redis metrics are also good, everything works. I've loaded Redis and everything is okay with it too.

What can be done about this problem? How to catch and handle it? It emerges too often. Usually with the GET state requests.

* Operating System: ubuntu
* Python Version: 3.10.6
* aiogram version: 3.0.0b7
* aiohttp version: 3.8.4
* uvloop version (if installed): 0.17.0

### Failure Logs

Ids and host are changed

[traceback.txt](https://github.com/aiogram/aiogram/files/12050350/traceback.txt)

**Comment by JrooTJunior** [comment]
This issue is not related to aiogram, aiogram RedisStorage uses redis-py library to connect to Redis, so, this issue is related to this library and Redis directly instead of aiogram, so, you should ask to help in redis-py bug-tracker.

You can check what is going on in Redis logs at the same time you got this error, maybe you can see the error on server side and understand why connection losted.
