### ISSUE TITLE
add Message.to_json() and Message.to_object() like in aiogram 2.x

### ISSUE THREAD

**Issue by makarworld** [aiogram/aiogram#1412]
### aiogram version

3.x

### Problem

`Message.to_json()` and `Message.to_object()` not exists yet in aiogram 3.x

### Possible solution

Migration it from aiogram 2.x

**Comment by Olegt0rr** [comment]
@makarworld, 
You should use:
- `message.model_dump()` instead of `Message.to_object()`
- `Message.model_dump_json()` instead of `Message.to_json()`

@aiogram/dev-team,
We also need to add it to our [migration guide](https://docs.aiogram.dev/en/dev-3.x/migration_2_to_3.html)
So I won't close this issue for now.
