### ISSUE TITLE
types.Message.edit_caption first positional argument is not caption but inline_message_id

### ISSUE THREAD

**Issue by iamnalinor** [aiogram/aiogram#1463]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Windows 11 23H2 x64

### Python version

3.12.2

### aiogram version

3.4.1

### Expected behavior

`types.Message.edit_caption` bound method's first argument is caption.
Calling `await message.edit_caption("Look at this amazing caption")` would edit the caption.

That's how it's already done in `types.Message.edit_text`.

### Current behavior

`types.Message.edit_caption` bound method's first argument is inline_message_id.
Calling `await message.edit_caption("Look at this amazing caption")` will not edit the caption but remove it. `"Look at this amazing caption"` will be passed as inline_message_id parameter value.

Right way to edit the caption will be `await message.edit_caption(caption="Look at this amazing caption")` or `await message.edit_caption(None, "Look at this amazing caption")`  which is not obvious.

### Steps to reproduce

1. Send an image to any chat with set caption
2. Edit the caption with `types.Message.edit_caption` passing the new caption as the first argument.
3. The caption disappeared.

### Code example

```python3
from aiogram import Bot
import asyncio

BOT_TOKEN = "your_token_here"
CHAT_ID = 123456

bot = Bot(BOT_TOKEN)


async def main():
    message = await bot.send_photo(CHAT_ID, "https://www.google.com/images/branding/googlelogo/1x/googlelogo_light_color_272x92dp.png", caption="Caption rev. 1")
    await asyncio.sleep(2)
    await message.edit_caption("Caption rev. 2")


asyncio.run(main())
```

**Comment by JrooTJunior** [comment]
All arguments has the same ordering as in the documentation (in due to codegenerateion can't be changed), so, you can't be sure that the positional argument is the same as you expect to see. In most of cases you should use keyword arguments instead.

In this specific case i agree it seems like `inline_message_id` should be passed automaticaly from the current message object and the argument should be removed.
Will be fixed in next release.

**Comment by JrooTJunior** [comment]
It is impossible to add auto-fill to this argument in due to this attribute was missing in the Message object.

It is also impossible to change the sequence because:
1. Other developers already depend on the sequence of arguments, changing the order will break an unspecified number of bots.
2. Shortcuts to methods are automatically generated based on the Telegram Bot API documentation, so introducing the ability to change the sequence during code generation introduces additional configuration complexity.
