### ISSUE TITLE
Can't use `message.answer` within `asyncio.gather`

### ISSUE THREAD

**Issue by leshchenko1979** [aiogram/aiogram#1467]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Latest Ubuntu

### Python version

3.12.3

### aiogram version

latest

### Expected behavior

```python
await asyncio.gather(message.answer("Hi"), state.clear())
```

### Current behavior

```
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 830, in gather
    if arg not in arg_to_fut:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'SendMessage'
```

### Steps to reproduce

```python
await asyncio.gather(message.answer("Hi"), state.clear())
```

### Code example

```python3
await asyncio.gather(message.answer("Hi"), state.clear())
```

**Comment by Olegt0rr** [comment]
```python
tasks = [
    asyncio.create_task(message.answer("Hi")),
    asyncio.create_task(state.clear()),
]
await asyncio.gather(*tasks)

```

**Comment by leshchenko1979** [comment]
I get the same message error when running:
```python
async with asyncio.TaskGroup() as tg:
    tg.create_task(message.answer("Hi!"))
```

Although the below works fine:
```python
await asyncio.create_task(message.answer("Hi!"))
```

**Comment by srbssv** [comment]
Doesn't work for me:

```py
await asyncio.create_task(message.answer("Hi!"))
```
The error:
```
TypeError: a coroutine was expected, got SendMessage
```

The above mentioned workaround with asyncio.gather(*tasks) didn't work as well.

Aiogram version: 3.3.0
Python version: 3.12.1

**Comment by JrooTJunior** [comment]
All shortcut methods returns instance of the method instead of the coroutine to make possible answer into the webhook (`return message.answer(...)`) inside handlers.

---

`TypeError: unhashable type: 'SendMessage'`

Method object is mutable, so that means it can't be used in places where hashable objects is expected like `asyncio.gather`.

---

Workarounds from the message above should works as well, but i recommend to use the shorter way, instead of using .emit method call it as bot(method):

```python
@my_router.message(Command("demo"))
async def command_demo(message: Message, bot: Bot):
    await asyncio.create_task(bot(message.answer("Hi!"))
```

---

In most of cases you shouldn't use API methods with gather because of Telegram Bot API rate limits, if you send too much API calls simultaneously you will be blocked.
