### ISSUE TITLE
Formatting nesting is broken

### ISSUE THREAD

**Issue by R0boji** [aiogram/aiogram#1516]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Windows 11 64 bit 

### Python version

3.12.0

### aiogram version

3.7.0

### Expected behavior

Method `as_<some markup_type>()` of Text class from `aiogram.utils.formatting` must return my string with right nesting.

### Current behavior

That method will return completely broken string, if I nest a lot of various formatting tools.
Example: ~**

### Steps to reproduce

1. Import all formatting classes, that inherited from `Text` class and that `Text` class.
2. Write down complicated instance of `Text` class with use of plain string, a lot of formatting classes and their nesting.
3. Display the Markdown v2 or HTML representing of that instance with methods `as_markdown()` and `as_html()`.

### Code example

```python3
from aiogram.utils.formatting import Strikethrough, Italic, Spoiler, Underline, Bold, Text

# First example
print(Text(Strikethrough(Bold(Bold("hethhtehtethhte", Underline("rrerehrehreh"))))).as_markdown())

# Second example
print(Text(Bold(Strikethrough(Bold(Bold(Bold("wrrwrwr"), "grrgr"))))).as_html())
```

### Logs

```sh
~**
<b><b><b><s><b>wrrwrwrgrrgr</b></s></b></b></b>grrgr
```

**Comment by JrooTJunior** [comment]
I should recheck this functionality.

It seems correct, but it is partially unprintable because some entities need to be separated by the "\r" character.
You can check it by sending to Telegram or checking the str or repr of the result.
Demo:

![image](https://github.com/aiogram/aiogram/assets/6726423/e8ef22d5-3fe6-4f3e-81ff-22472ba99205)


---

You don't need to convert this formatting to HTML or even MarkdownV2 because it can be used directly to sent to the Telegram Bot API as text with entities.
https://docs.aiogram.dev/en/dev-3.x/utils/formatting.html#basic-scenario

**Comment by R0boji** [comment]
Ok, thank for your answer!
