### ISSUE TITLE
Chat.update_chat() Failing

### ISSUE THREAD

**Issue by Tr-Jono** [aiogram/aiogram#178]
## Context

* Operating System: Windows 10
* Python Version: 3.7.1
* aiogram version: 2.2
* aiohttp version: 3.5.4
* uvloop version (if installed): N/A

## Expected Behavior

`Chat.update_chat()` updates the chat successfully.

## Current Behavior

An error is raised.

### Steps to Reproduce

1. You run `.update_chat()` on a `Chat` instance
(an error is raised for private and public supergroups, not sure for other chat types)

### Failure Logs

```
Traceback (most recent call last):
  ...
  File ..., line ..., in ...
    await chat.update_chat()
  File "C:\...\aiogram\types\chat.py", line 99, in update_chat
    self[key] = value
  File "C:\...\aiogram\types\base.py", line 223, in __setitem__
    raise KeyError(key)
KeyError: 'permissions'
```

**Comment by Birdi7** [comment]
This error isn't raised in private chats. In supergroups It happens because chat info has an additional field `permissions` which doesn't appear in the info of private chats. And, field `permissions` isn't declared [here](https://github.com/aiogram/aiogram/blob/f77b752c60180469c55058e7c036d0b0d6598c4b/aiogram/types/chat.py#L32), so it may be the reason of the problem

**Comment by JrooTJunior** [comment]
Yes. Attribute `permissions` is added in Bot API 4.4 and that is documented only now.

This error will be fixed in next release.

**Comment by JrooTJunior** [comment]
Already fixed in dev-2.x branch. Soon it will be available on pypi

**Comment by JrooTJunior** [comment]
Fixed.
