### ISSUE TITLE
Emit a warning when command starts with command prefix

### ISSUE THREAD

**Issue by evgfilim1** [aiogram/aiogram#206]
## Example code
```python
@dp.message_handler(commands=["/help"])
async def get_help(message):
    await message.reply(HELP_TEXT)
```
## Expected output
```
UserWarning: command "/help" starts with command prefix, so handler will trigger only on "//help" command. Remove leading command prefix to avoid this behavior.
```
## Actual output
None

**Comment by ShubhamBhut** [comment]
Hey @evgfilim1 ,

I want to work on this issue and I saw last PR was closed due to confusion whether the user should be warned, or just pass the command without double prefixes and let the user use both styles:  ['/start', '/help'] and ['start', 'help']. Can you tell me which approach is recommended ?

**Comment by Olegt0rr** [comment]
IMHO, it's easier to make `.lstrip("/")`, than make warnings
