### ISSUE TITLE
Thumb with file_id in inlinequery mode

### ISSUE THREAD

**Issue by antibagr** [aiogram/aiogram#411]
Hello. You have awesome library, but I bumped into a bug ( maybe it's a problem of telegram API)

• Win 10 x64
• Python 3.8.5
• aiogram 2.9

In inline_handler I generate InlineQueryResultArticle with thump_url.
the 'thumb_url' is generating with f-string formatting `f"http://api.telegram.org/file/bot{BOT_TOKEN}/{file_path}"`
Where file_path created as shown:
```
file_object = await bot.get_file(file_id=file_id_from_database)
file_path = file_object.file_path
```

So the full link looks like https://api.telegram.org/file/bot<token>/photos/<file_name>.jpg depends on extension ( I've tried jpg,png)

**While I can access these photos with bot.send_photo (using the same link), I'm not able to see them in inline mode.**

Thank you in advance for any feedback!

![problem](https://user-images.githubusercontent.com/16188591/91784944-c6f61480-ec0c-11ea-8ba7-f6bd0a852128.png)

**Comment by evgfilim1** [comment]
Is it still reproducible?

**Comment by nuckle** [comment]
The issue is still relevant. 
I think that it's caused by `https://api.telegram.org/file/bot<token>/<file_path>` not being an actual direct URL to a file. Basically, it's just an API call. This can be confirmed in `wget` which returns mime-type `application/octet-stream` instead of, for example, `image/png`.  

For example, if you try to paste a regular direct link (like `https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Telegram_2019_Logo.svg/1024px-Telegram_2019_Logo.svg.png`) it'll work just fine. But if you try to use something like files from [temp.sh](https://temp.sh) which will give you link like this `http://temp.sh/sFGtP/file.png`, it won't work because it's not a direct file (so, no previews in telegram client and mime-type will be `text/html`).
