### ISSUE TITLE
Possible wrong query.message.from_user.id in query: types.CallbackQuery

### ISSUE THREAD

**Issue by altuhovsu** [aiogram/aiogram#471]
## Context

May be not a bug, but it will be good, if query.message.from_user.id in types.CallbackQuery will return an User ID, not a bot ID.

* Operating System: Kubuntu 20.10
* Python Version: 3.8.6
* aiogram version: 2.11.2
* aiohttp version: 3.7.2

## Expected Behavior

query.message.from_user.id returns an ID of the original user, not bot

## Current Behavior

query.message.from_user.id returns an ID of the bot

### Steps to Reproduce

```
@dp.callback_query_handler(text='test')
async def test_callback_handler(query: types.CallbackQuery):
logging.info('user id from query: %s', str(query.from_user.id)) # ID will be correct = user
logging.info('user id from message: %s', str(query.message.from_user.id)) # ID will be incorrect = bot, shoud be the same as query.from_user.id
```

**Comment by evgfilim1** [comment]
Hello, @altuhovsu. It's not a bug, the behavior is intended because the callback query's message belongs to the bot (as it sent the message with inline keyboard), so `query.message.from_user.id` returns bot id. You can get an ID of original user by using `query.from_user.id` (notice no `message` here). If you have further questions, feel free to ask them in our Telegram community: [@aiogram](https://t.me/aiogram).
