### ISSUE TITLE
Webhook isn’t running async?

### ISSUE THREAD

**Issue by fablee1** [aiogram/aiogram#638]
I made a bot with AIOGRAM, I have a handler that does some logic and using asyncio.sleep(10), deletes a message after 10 seconds

in polling mode everything works great, I can spam 10 messages in the chat and they all immediately will be deleted after 10 seconds from sending them

but when I made up my local webhook, and also the same is when hosting on heroku with webhook, when sending the messages, it makes a queue from them and processes one by one, so it’s like one message, then 10 seconds, the second, 10 seconds the third… so in polling it works perfect, in webhook mode it doesn’t seem to run asynchronously, I tried to find help in the aiogram telegram chat but nobody could help me.
This is a very strange behaviour as if webhook can’t process them at one time

**Comment by fablee1** [comment]
In polling mode:
![polling](https://user-images.githubusercontent.com/58670304/126380050-587d7496-591a-471e-85ad-3e4bc94feafe.gif)

And in webhook mode:
![webhook](https://user-images.githubusercontent.com/58670304/126379984-d599f02c-8f53-4ea0-95b2-45a911e1f5a3.gif)

**Comment by evgfilim1** [comment]
Hi, @fablee1.
I guess this happens because aiogram supports [replying into webhook](https://core.telegram.org/bots/faq#how-can-i-make-requests-in-response-to-updates), so the handler has to return anything before the next update could be processed. If you're not using this feature and you don't really need it (are you returning nothing from the handler?), you can safely use `dp = Dispatcher(run_tasks_by_default=True)` or just in your problematic handler `@dp.message_handler(..., run_task=True)`.

**Comment by fablee1** [comment]
@evgfilim1 thanks for your reply, and making it clear why this happened to me, it's really strange it's so hard to find any info about that, but thanks for your hard work!
