### ISSUE TITLE
Message.md_text don`t work with italic and underline

### ISSUE THREAD

**Issue by twistfire92** [aiogram/aiogram#705]
I send 
![image](https://user-images.githubusercontent.com/48478011/134291216-1c725765-2b61-4627-941e-08b01a5f6a10.png)

`message.md_text` returned
![image](https://user-images.githubusercontent.com/48478011/134291336-bd28b3a9-a85d-49e5-9e59-bf66ce29b689.png)

**Comment by JrooTJunior** [comment]
Just try to send resulted string back to the Telegram (`await message.answer(message.md_text, parse_mode='MarkdownV2')`)

Fix from #704 totally is not correct because without adding \r nested italic underline entities doesn't works as described in [Bot API Docs](https://core.telegram.org/bots/api#markdownv2-style) and you don't see some words because in this place \r is used as move cursor to position 0 at line but the resulting string is correct
