### ISSUE TITLE
Method to remove InlineKeyboardButton from markup

### ISSUE THREAD

**Issue by Sciti** [aiogram/aiogram#851]
As i understand, now InlineKeyboardMarkup is just a dict with lists, so method like pop() will be useful and make code cleaner, at least for newbies like me. 
For now, to make dynamic inline keyboard with deleting buttons after user clicks on them i need to recreate entire markup from changed list, but it can be simplified by using InlineKeyboardMarkup.pop() or something like that.

**Comment by Olegt0rr** [comment]
Since it's a dict with list of lists - .pop() method may mess user: is it pop of latest button? or is it pop of latest row? or is it pop of latest button of the first row? so many solutions...

It seems not so scare to create another one shortcut.
I'm not against this solution, but it's redundant for me.

### Simple workaround
```python
latest_button = markup.inline_keyboard[-1].pop()
```
