### ISSUE TITLE
`towncrier` is not in developer requirements

### ISSUE THREAD

**Issue by Olegt0rr** [aiogram/aiogram#878]
## Context

Towncrier is absent in developer requirements, but it's required for any pull request.
Now it's listed in production requirements, but I can't imagine any production needs for it.

## Expected Behavior

Towncrier is installed by default for every developer.

## Current Behavior

Towncrier is not installed for developers and should be installed manually to make Changelog record and pass Changelog Quality Gate for PR

**Comment by JrooTJunior** [comment]
Is not a bug because towncrier located with `docs` dependencies:
https://github.com/aiogram/aiogram/blob/930bca0876a15a5d3d12a1b773f35c9bc7a5cafe/pyproject.toml#L60
https://github.com/aiogram/aiogram/blob/930bca0876a15a5d3d12a1b773f35c9bc7a5cafe/pyproject.toml#L96-L109

For development you will need to install all extras of this package explicitly as described in `Makefile`:
https://github.com/aiogram/aiogram/blob/930bca0876a15a5d3d12a1b773f35c9bc7a5cafe/Makefile#L49-L51

**Comment by JrooTJunior** [comment]
Also.. This issue can be converted to task because we need to have an complete developer guide

**Comment by evgfilim1** [comment]
> Also.. This issue can be converted to task because we need to have an complete developer guide

I guess it'd be better to create a new issue based on this. Let me do this.
