### ISSUE TITLE
[Question] Does aiogram support multithreading? Is that what the dp.async_task handler is for?

### ISSUE THREAD

**Issue by LikeMoneySecretly** [aiogram/aiogram#918]
Does aiogram currently support assigning command handlers to new threads/starting tasks in new threads from commands to the telegram bot? The reason I'm asking is that I have a variety of intensive I/O operations that really need to be run in a multithreaded capacity in order for them to function.

**Comment by JrooTJunior** [comment]
> Does aiogram support multithreading?

This question is not related to `aiogram`. Just read the docs how asyncio works.

---

> Is that what the dp.async_task handler is for?

This decorator is not related to multithreading. This decorator is needed to run handler in asyncio task without waiting the response from the handler as described in method doc-string: https://github.com/aiogram/aiogram/blob/a0fb37a54de3232213a9a6e1182490a422834ad4/aiogram/dispatcher/dispatcher.py#L1375-L1390

---

If you mean disk I/O operations or blocking code you should use [asyncio.to_thread
](https://docs.python.org/3/library/asyncio-task.html#asyncio.to_thread) function to prevent to block event-loop.

If you mean network I/O with asynchronous connectors you should use [asyncio.create_task](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task)

In both cases you can use distributed task queue (Celery, arq, faust etc.) and this is recommended solution.
For example inside bot handler made answer to used like "Generating report, wait few minutes i'll made it for you" and spawn task into external queue and process it with finally response to the user.

---

By the way, you should not run long-running inside handlers directly because the answer to the Telegram should be taken soon as possible and also Users wont wait too long for answers.

**Comment by JrooTJunior** [comment]
I'll close this issue, if you have additional questions you can re-open this issue or create new-one
